apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ./certificates.yaml
- ./services.yaml
- ./endpoints.yaml
- ./servertransports.yaml
- ./ingresses.yaml

# - ./tailscale.yaml
