---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab-heyser-xyz-tls
spec:
  subject:
    organizations:
    - Heyser
  secretName: wildcard-homelab-heyser-xyz-tls
  dnsNames:
  - '*.homelab.heyser.xyz'
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
