apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ./pvc.yaml
- ./secret.yaml
- ./database-objectstore.yaml
- ./database.yaml
- ./database-backup.yaml
- ./certificate.yaml
- ./immich.yaml
- ./loadbalancer.yaml
- ./tailscale.yaml
