apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ./serviceaccount.yaml
- ./secret.yaml
- ./configmap.yaml
- ./clusterrbac.yaml
- ./service.yaml
- ./deployment.yaml
- ./ingress.yaml
- ./tailscale.yaml
